# Generated by Django 2.1.2 on 2018-10-11 19:21

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='type',
        ),
        migrations.AddField(
            model_name='ticket',
            name='category',
            field=models.CharField(choices=[('BUG', 'Bug'), ('FEATURE', 'Feature')], default='BUG', max_length=7),
        ),
        migrations.AddField(
            model_name='ticket',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 11, 19, 21, 53, 836672, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='ticket',
            name='last_modified_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 11, 19, 21, 53, 836726, tzinfo=utc)),
        ),
    ]
