# Generated by Django 2.1.2 on 2018-10-11 21:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tickets', '0007_auto_20181011_1942'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='upvoted_by',
            field=models.ManyToManyField(related_name='ticket_upvoters', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ticket_creator', to=settings.AUTH_USER_MODEL),
        ),
    ]
