# Generated by Django 2.1.2 on 2018-10-12 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0011_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='text',
            new_name='comment',
        ),
    ]
